[package]
name = "clutch_node"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.22.0"
sha2 = "0.9"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
secp256k1 = { version = "0.28.2", features= ["recovery","rand"] }
rand = "0.8.4"
hex = "0.4.3"