services:
  node1:
    image: clutch-node
    container_name: clutch-node-container-node1
    networks:
      - clutch-network
    ports:
      - "8081:8081"
      - "4001:4001"
      - "3001:3001"
    volumes:
      - clutch-config:/usr/src/clutch-node/config
    command: ["--env", "node1"]

  node2:
    image: clutch-node
    container_name: clutch-node-container-node2
    networks:
      - clutch-network
    ports:
      - "8082:8082"
      - "4002:4002"
      - "3002:3002"
    volumes:
      - clutch-config:/usr/src/clutch-node/config
    command: ["--env", "node2"]

  node3:
    image: clutch-node
    container_name: clutch-node-container-node3
    networks:
      - clutch-network
    ports:
      - "8083:8083"
      - "4003:4003"
      - "3003:3003"
    volumes:
      - clutch-config:/usr/src/clutch-node/config
    command: ["--env", "node3"]

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    networks:
      - clutch-network   
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
      - GF_USERS_ALLOW_SIGN_UP=false 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    networks:
      - clutch-network
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus  
      - E:/docker_shared/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  seq:
    image: datalust/seq
    container_name: seq-container
    networks:
      - clutch-network
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    environment:
      - ACCEPT_EULA=Y  
  
networks:
  clutch-network:  # Shared network for all services

volumes:
  clutch-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/source/clutch-node/config

  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:/docker_shared/grafana  

  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:/docker_shared/prometheus 

  seq-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:/docker_shared/seq
