{
 "title": "Clutch-Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latest Block Index",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latest_block_index", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latest Block (Node 1)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "latest_block{job=\"node1\"}",
     "legendFormat": "{{block_hash}}"
    }
   ]
  },
  {
   "title": "Latest Block (Node 2)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "latest_block{job=\"node2\"}",
     "legendFormat": "{{block_hash}}"
    }
   ]
  },
  {
   "title": "Latest Block (Node 3)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "latest_block{job=\"node3\"}",
     "legendFormat": "{{block_hash}}"
    }
   ]
  }
 ]
}