name: Branch Protection Enforcement

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main, develop, 'release/*']

permissions:
  contents: read
  pull-requests: read
  statuses: read

jobs:
  enforce-protection:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Check PR Requirements
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({ owner, repo, pull_number: number });
            
            // Check if PR is from Mehran Mazhar (bypass restrictions)
            const isMehran = pr.user.login === 'MehranMazhar';
            
            if (isMehran) {
              console.log('✅ PR from Mehran Mazhar - bypassing restrictions');
              return;
            }
            
            // Check required status checks
            const statuses = await github.rest.repos.getCombinedStatusForRef({
              owner,
              repo,
              ref: pr.head.sha
            });
            
            const requiredChecks = ['build', 'test', 'lint'];
            const missingChecks = requiredChecks.filter(check => 
              !statuses.statuses.some(status => status.context.includes(check))
            );
            
            if (missingChecks.length > 0) {
              core.setFailed(`Missing required status checks: ${missingChecks.join(', ')}`);
            }
            
            // Check if PR has required reviews
            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: number
            });
            
            const approvedReviews = reviews.data.filter(review => 
              review.state === 'APPROVED'
            );
            
            if (approvedReviews.length === 0) {
              core.setFailed('PR requires at least one approval');
            }
            
            console.log('✅ PR meets all requirements');

  maintainer-bypass:
    runs-on: ubuntu-latest
    if: github.actor == 'MehranMazhar'
    
    steps:
      - name: Maintainer Bypass
        uses: actions/github-script@v7
        with:
          script: |
            console.log('🔓 Maintainer bypass enabled for Mehran Mazhar');
            console.log('You can push directly to protected branches');
            console.log('Use responsibly for rapid development!');

  security-scan:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref.startsWith('refs/heads/release/')
    
    steps:
      - name: Security Scan
        uses: actions/github-script@v7
        with:
          script: |
            console.log('🔒 Running security scan for protected branch');
            // Add security scanning logic here
            console.log('Security scan completed');
